from enum import Enum


class YouTubeVideoStates(Enum):
    TO_BE_DOWNLOADED = "TO_BE_DOWNLOADED"
    UPLOADED = "UPLOADED"
    NOT_A_SERMON = "NOT A SERMON"
    NEW = "NEW"
    DOWNLOADED_NOT_UPLOADED = "DOWNLOADED_NOT_UPLOADED"
